name: CI

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: npx @redocly/openapi-cli lint ./openapi/openapi.yaml
